version: '3.9'
services:
  #MongoDB service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      -  mongo_db:/data/db

  #NodeJS service
  api:
    build: .
    ports:
      - 4000:8080
    environment:
      MONGO_URI: mongodb+srv://myDB:myDB123@cluster0.pudgs.mongodb.net/reunion?retryWrites=true&w=majority
      JWT_SECRET: mahendrasinghdhoni
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}    